### ISSUE TITLE
Unable to pip install caravel

### ISSUE THREAD

**Issue by dhafley** [tstowe/GlobalAvgTemperatures#3]
After integrating changes in PR1, this is the output for an attempted install of caravel.  This is output from command line in guest os.  Ansible task also fails.

Ansible Task:

```
   - name: Install caravel
     pip: name=caravel state=present

```

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_vagrant/cryptography/setup.py", line 335, in <module>

```
**keywords_with_side_effects(sys.argv)
```

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

```
_setup_distribution = dist = klass(attrs)
```

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in **init**

```
self.fetch_build_eggs(attrs.pop('setup_requires'))
```

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

```
replace_conflicting=True
```

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve

```
dist = best[req.key] = env.best_match(req, ws, installer)
```

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match

```
return self.obtain(req, installer) # try and download/install
```

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain

```
return installer(requirement)
```

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

```
return cmd.easy_install(req)
```

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install

```
return self.install_item(spec, dist.location, tmpdir, deps)
```

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item

```
dists = self.install_eggs(spec, download, tmpdir)
```

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs

```
return self.build_and_install(setup_script, setup_base)
```

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install

```
self.run_setup(setup_script, setup_base, args)
```

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1028, in run_setup

```
raise DistutilsError("Setup script exited with %s" % (v.args[0],))
```

distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_vagrant/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-ZHG8B6-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_vagrant/cryptography
Storing debug log for failure in /home/vagrant/.pip/pip.log

```
```

**Comment by tstowe** [comment]
@dhafley Jumping in to see what's going on, I didn't have issues with this step last week and now I'm getting this same error, but it happens when trying to install Ansible dependencies (so very early in the build). [StackOverflow](http://stackoverflow.com/questions/26053982/error-setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-wit) is suggesting there might be another package needed, so I'm going to try this and report on what happens.

**Comment by tstowe** [comment]
@dhafley ~~[This change to the Ansible plugin](https://github.com/vovimayhem/vagrant-guest_ansible/issues/13) might also be the culprit, since it's installing the required dependencies for cryptography (libffi and libssl) in a different Python directory than Python 2.7 (needed for Caravel). Going to poke around the VM and will continue updating as I find things.~~

UPDATE: I misread the issue for the the plugin originally.  It's part of the issue since it hasn't updated in over a year. The suggested change is needed to work with Ansible now since something changed recently within Ansible. That change was not committed to the main project, so a local version of the plugin with the change made to its guest_script.sh would be needed. Still trying to figure out how to install a local version of the plugin to test this out, will update if I get it going.

**Comment by tstowe** [comment]
Here's a workaround: 
`vagrant ssh`
`sudo apt-get install libffi-dev`
`sudo apt-get install libssl-dev`
Exit the VM by hitting ctrl+D
Then run 
`vagrant provision`
